name: Deploy Vue

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: yarn install --ignore-optional --pure-lockfile --non-interactive
    - name: Build site
      run: yarn build
    - name: Deploy with github-pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.PUBLIC_REPO }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: dist
