name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run compile
    - run: npm run build
    - uses: LuisEnMarroquin/gh-pages-publish@v2.3.2
      with:
        FOLDER: dist
        SSHKEY: ${{ secrets.SSH }}
